### ISSUE TITLE
Login and Signup pages are both blank.

### ISSUE THREAD

**Issue by jelissa** [themeteorchef/writing-an-api#2]
The app has successfully started after all the depended packages are installed/updated. However, the login and signup pages are both coming up as blank pages. Can you please let me know if there is some issues with the iron-router, or if I am missing some steps? Please advise.

Thanks!

**Comment by themeteorchef** [comment]
Hi there :) This tutorial relies on React Router, not Iron Router. If you have both installed there's likely a conflict between them that's preventing either from rendering the routes.

**Comment by jelissa** [comment]
Thank you for the quick response. I mistakenly thought that the package was using iron router due to the routing syntax is very similar to iron router's. 

I have limited knowledge of react router; I have updated the front-end routing to flow router + blaze while keeping iron router for the backend api routing. I did this because iron router was not behaving properly with my docker setup.

**Comment by jwjordan** [comment]
The very first step in the tutorial on this says to install Iron router: https://themeteorchef.com/tutorials/writing-an-api

**Comment by themeteorchef** [comment]
@jwjordan you're right...reviewing this now I can't understand why I suggested this was based on React Router 😕. Are the pages in question still rendering as blanks when using Iron Router?

**Comment by jwjordan** [comment]
The codebase works if you don't try to upgrade Meteor.  So, the basic answer is that it works fine with Iron Router if you clone the repo and run meteor.  However, I could not for the life of me upgrade to the latest version of meteor (meteor update; meteor update --all-packages) and get it working. At that point I was getting iron router errors as if routes weren't defined at all.

**Comment by themeteorchef** [comment]
@jwjordan ah okay, thank you for clarifying. Unfortunately there's not much we can do on our end as work on Iron Router stopped a ways back :/ if there's a specific error being thrown that you can share (aside from the blank screen), I can try to help debug!

**Comment by jwjordan** [comment]
Aw man, I didn't even realize Iron Router wasn't in active dev!  I don't have the specific error, because after learning a *ton* from your tutorial (thanks BTW), I came to the realization that what I really needed was DDP and not an API.  So, I didn't chase the error much longer after I originally posted here.

**Comment by themeteorchef** [comment]
@jwjordan ah, gotcha :) No worries. In that case I'm going to leave this issue closed as it seems like the trouble is a conflict between Iron Router and newer releases of Meteor. Adding something to our list now to do a refactor of this so there's no dependency on IR.
